### ISSUE TITLE
Cannot Save

### ISSUE THREAD

**Issue by ultraflame4** [TristenHarr/MyPyBuilder#1]
Game Freezes when i try to
Da logs:
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\ultra\Desktop\MyPyBuilder-master\GuiBuilder\BUILDER\ProjectTemplate\Tabs\FrameTab\FrameTabBuild.py", line 443, in save_project
    shutil.rmtree(self.root_path)
  File "C:\Program Files\Python37\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Python37\lib\shutil.py", line 374, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Program Files\Python37\lib\shutil.py", line 371, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\ultra\\Desktop\\MyPyBuilder-master\\GuiBuilder\\PROJECTS\\Autoclicker'
```

**Comment by ultraflame4** [comment]
Edit: Fixed issue by creating new folder in GuiBuilder\\PROJECTS
